config/routes.rb
Rails.application.routes.draw do
  
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members
  root 'site/home#index'
  

end

app/models/ad.rb
class Ad < ActiveRecord::Base
  belongs_to :member
  belongs_to :category
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Constantes
  ROLES = {:full_access => 0, :restricted_access => 1}

  # Enums
  enum role: ROLES

  # Scopes
  scope :with_full_access, -> { where(role: ROLES[:full_access]) }
  scope :with_restricted_access, -> { where(role: ROLES[:restricted_access]) }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/category.rb
class Category < ActiveRecord::Base
	validates_presence_of :description
end

app/models/member.rb
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Pundit
  include Pundit

  # Manages Pundit Errors 
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # Set Layout
  layout :layout_by_resource

  protected
    # Layout per resource_name
    def layout_by_resource
    	if devise_controller? && resource_name == :admin
    		"backoffice_devise"
    	else
    		"application"
    	end
    end

    def user_not_authorized
      flash[:alert] = "Você não está autorizado a executar essa ação."
      redirect_to(request.referrer || root_path)
    end

end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController

	before_action :set_admin, only: [:edit, :update, :destroy]

	after_action :verify_authorized, only: [:new, :destroy]
	after_action :verify_policy_scoped, only: :index


	def index
		#admins = Admin.all
		#@admins = Admin.with_restricted_access
		@admins = policy_scope(Admin)
	end

	def new
		@admin = Admin.new
		authorize @admin
	end

	def create
		@admin = Admin.new(params_admin)
		if @admin.save
			redirect_to backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @admin.update(params_admin)
			AdminMailer.update_email(current_admin, @admin).deliver_now
			redirect_to backoffice_admins_path, notice: "Administrador atualizado com sucesso!"
		else
			render :edit
		end
	end

	def destroy
		authorize @admin
		admin_name = @admin.name

		if @admin.destroy
			redirect_to backoffice_admins_path, notice: "Administrador excluído com sucesso!"
		else
			render :index
		end

	end
		
	private

		def set_admin
			@admin = Admin.find(params[:id])
		end

		def params_admin
			passwd = params[:admin][:password]
			passwd_confirmation = params[:admin][:password_confirmation]

		if passwd.blank? && passwd_confirmation.blank?
			params[:admin].except!(:password, :password_confirmation)
		end
			params.require(:admin).permit(policy(@admin).permitted_attributes)
		end

end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController

	before_action :set_category, only: [:edit, :update]

	def index
		@categories = Category.all
	end

	def new
		@category = Category.new
	end

	def create
		@category = CategoryService.create(params_category)
		
		unless @category.errors.any?
			redirect_to backoffice_categories_path, notice: "Categoria cadastrada com sucesso!"
		else
			render :new
		end
	end

	def edit
	end

	def update
		if @category.update(params_category)
		redirect_to backoffice_categories_path, notice: "Categoria atualizada com sucesso!"
		else
			render :edit
		end
	end

	private

		def set_category
			@category = Category.find(params[:id])
		end

		def params_category
			params.require(:category).permit(:description)
		end

end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
	attr_accessor :category

	def self.create(params_category)
		@category = Category.new(params_category)

		if @category.valid?
			@category.save
		end

		@category
	end


end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
	def index
	end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController

	def edit

		@admin = Admin.find(params[:id])
		
		respond_to do |format|
			format.js
		end
	end

	def create

	begin

		AdminMailer.send_message(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text'])
		@notify_message = "Email enviado com sucesso!"
		@notify_flag = "success" 

	rescue
		@notify_message = "Erro ao enviar email. Tente novamente"
		@notify_flag = "error"
	end
		respond_to do |format|
			format.js
		end
		
	end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
	before_action :authenticate_admin!
	layout "backoffice"

	def pundit_user
		current_admin # current_user to Pundit		
	end
end

app/controllers/site/home_controller.rb
class Site::HomeController < ApplicationController
  layout "site"

  def index
  	@categories = Category.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
	OptionsForRoles = Struct.new(:id, :description)

	def options_for_roles
		Admin.roles_i18n.map do |key, value|
			OptionsForRoles.new(key, value)
		end
	end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/helpers/site/home_helper.rb
module Site::HomeHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/backoffice/admins/edit.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Editando Adminstradores"} %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        Listando Administradores

        <% if policy(@admins).new? %>
            <%= link_to new_backoffice_admin_path, class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px;" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        <% else %>
            <%= link_to '#', disabled: "disabled", class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px;" do %>
                <i class="fa fa-plus"></i>
            <% end %>
        <% end %>
        
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>E-mail</th>
                        <th>Tipo de Acesso</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    <% @admins.each do |admin| %>
                    <tr>
                        <td><%= admin.id %></td>
                        <td><%= admin.name %></td>
                        <td><%= admin.email %></td>
                        <td><%= admin.role_i18n %></td>
                        <td style="width: 150px;">
                            <%= link_to edit_backoffice_send_mail_path(admin), class: "btn btn-info btn-circle", remote: true do %>
                                <i class="fa fa-envelope"></i>
                            <% end %>
                            <%= link_to edit_backoffice_admin_path(admin), class: "btn btn-primary btn-circle" do %>
                                <i class="fa fa-edit"></i>
                            <% end %>

                            <% if (current_admin.id != admin.id) && policy(@admins).destroy? %>  
                                <%= link_to backoffice_admin_path(admin), method: :delete, class: "btn btn-danger btn-circle", data: {confirm: t('messages.confirm_with', item: admin.name)} do %>
                                    <i class="fa fa-minus"></i>
                                <% end %>
                            <% else %>
                                <%= link_to '#', disabled: "disabled", class: "btn btn-danger btn-circle" do %>
                                    <i class="fa fa-minus"></i>
                                <% end %>
                            <% end %>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

<%= render partial: 'backoffice/admins/shared/send_mail_modal' %>

app/views/backoffice/admins/new.html.erb
<%= render partial: "backoffice/admins/shared/form", locals: {action: "Novo Administrador"} %>

app/views/backoffice/admins/shared/_form.html.erb
   <h1 class="page-header">Administradores</h1>

   <% if @admin.errors.any? %>
   <div class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
    <ul>
      <% @admin.errors.full_messages.each do |message| %>
      <li><%= message %></li>   
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="panel panel-default">
    <div class="panel-heading">
      <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
      <div class="col-lg-6">
        <%= form_for([:backoffice, @admin]) do |f| %>
        <div class="form-group">
           <%= f.label :name %>
           <%= f.text_field :name, class: "form-control", placeholder: "Nome do Administrador" %>
         </div>

         <div class="form-group">
           <%= f.label :email %>
           <%= f.text_field :email, class: "form-control", placeholder: "Ex: teste@teste.com" %>
          </div>


         <% if policy(@admin).new? %>
           <div class="form-group">
             <%= f.label :role %>
             <%= f.collection_radio_buttons(:role, options_for_roles, :id, :description) do |b| %>
             <div class="radio">
             <%= b.label { b.radio_button + b.text} %>
            </div>
           <% end %>
          </div>
        <% end %>

         <div class="form-group">
           <%= f.label :password %>
           <%= f.password_field :password, class: "form-control", placeholder: "Senha" %>
         </div>
         
         <div class="form-group">
           <%= f.label :passowrd_confirmation %>  
           <%= f.password_field :passowrd_confirmation, class: "form-control", placeholder: " Confirmação da Senha" %>
       </div>

       <button type="submit" class="btn btn-default">Salvar</button>
       <% end %>
     </div>
     <!-- /.panel-body -->
   </div>

app/views/backoffice/admins/shared/_send_mail_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel"><%= t('labels.new_message') %></h4>
      </div>

      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do  %>

          <div class="form-group">
            <label for="recipient-name" class="control-label"><%= t('labels.recipient') %></label>
            <%= text_field_tag(:'recipient-text', nil, class: "form-control", readonly: "readonly") %>
          </div>
      
          <div class="form-group">
            <label for="recipient-name" class="control-label"><%= t('labels.subject') %></label>
            <%= text_field_tag(:'subject-text', nil, class: "form-control", required: "required") %>
          </div>
      


          <div class="form-group">
            <label for="message-text" class="control-label"><%= t('labels.message') %></label>
            <%= text_area_tag(:'message-text', nil, class: "form-control", required: "required") %>
          </div>
   

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('buttons.close') %></button>
        <%= submit_tag t('buttons.send_message'), class: "btn btn-primary" %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/categories/edit.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Editando Categoria"} %>

app/views/backoffice/categories/index.html.erb
<h1 class="page-header">Categorias</h1>

<div class="panel panel-default">
    <div class="panel-heading">
        Listando Categorias
        <%= link_to new_backoffice_category_path, class: "btn btn-success btn-circle pull-right", style: "margin-top: -5px;" do %>
        <i class="fa fa-plus"></i>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Descrição</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.id %></td>
                        <td><%= category.description %></td>
                        <td style="width: 150px;">
                            <%= link_to edit_backoffice_category_path(category), class: "btn btn-primary btn-circle" do %>
                            <i class="fa fa-edit"></i>
                            <% end %>
                            <button type="button" disabled="disabled" class="btn btn-danger btn-circle"><i class="fa fa-minus"></i></button>
                        </td>
                    </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
    <!-- /.panel-body -->
</div>

app/views/backoffice/categories/new.html.erb
<%= render partial: "backoffice/categories/shared/form", locals: {action: "Nova Categoria"} %>

app/views/backoffice/dashboard/index.html.erb
 <h1 class="page-header">Dashboard</h1>
 <%# if notice %>
 <!-- <div class="alert alert-success alert-dismissable">
 	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
 	<%#= notice %>
  </div>
 <%# end %>

app/views/backoffice/send_mail/create.js.erb
$(function(){
	let $sendMailModal = $('#sendMailModal');

	//Shows Modal
	$('#sendMailModal').modal('hide');
	$('#subject-text').val('');
	$('#message-text').val('');

	// Show Message
	$.notify('<%= @notify_message %>', "<%= @notify_flag %>");
});

app/views/backoffice/send_mail/edit.js.erb
$(function(){
	let $sendMailModal = $('#sendMailModal');

	//Setting email and name on Form
	$('#recipient-text').val('<%= @admin.email %>');
	$('h4.modal-title').text('Enviar mensagem para <%= @admin.name %>');
	
	//Shows Modal
	$('#sendMailModal').modal();

	//Set focus on 'Subject Text' after modal is shown
	$('#sendMailModal').on('shown.bs.modal', function() {
		$('#subject-text').focus();
	})
});

app/views/layouts/backoffice_shared/_navigation.html.erb
 <!-- Navigation -->
 <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="index.html">BackOffice - THEPI Store</a>
    </div>
    <!-- /.navbar-header -->

    <ul class="nav navbar-top-links navbar-right">

    <li><%= current_admin.email %></li>

        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-user">
                <li>
                    <%= link_to destroy_admin_session_path, method: :delete do %>
                    <i class="fa fa-sign-out fa-fw"></i> 
                    Sair
                    <% end %>
                </li>
            </ul>
            <!-- /.dropdown-user -->
        </li>
        <!-- /.dropdown -->
    </ul>
    <!-- /.navbar-top-links -->

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
            <ul class="nav" id="side-menu">
                <li>
                    <%= link_to backoffice_path do %>
                    <i class="fa fa-dashboard fa-fw"></i> Dashboard
                    <% end %>
                </li>
                <li>
                <%= link_to backoffice_categories_path do %>
                    <i class="fa fa-th-list fa-fw"></i> Categorias
                    <% end %>
                </li>
                 <li>
                <%= link_to backoffice_admins_path do %>
                    <i class="fa fa-users fa-fw"></i> Administradores
                    <% end %>
                </li>
            </div>
            <!-- /.sidebar-collapse -->
        </div>
        <!-- /.navbar-static-side -->
    </nav>

app/views/layouts/site_shared/_footer.html.erb
<div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

app/views/layouts/site_shared/_navigation.html.erb
<!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Start Bootstrap</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="#">About</a>
                    </li>
                    <li>
                        <a href="#">Services</a>
                    </li>
                    <li>
                        <a href="#">Contact</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/members/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>